### ISSUE TITLE
NC 28 compatibility

### ISSUE THREAD

**Issue by Mer0me** [ACTom/files_mindmap#191] opened 2023-12-17 09:56 UTC
The app seems to be incompatible with NC28. I cannot create new mind map and cannot open existent mind map, even if the app is installed and info.xml claim it is compatible with NC 28.

**Comment by les-les** [comment] 2023-12-17 19:22
same here NC 28.0.0

**Comment by artonge** [comment] 2023-12-21 10:56
Should be fixed by https://github.com/ACTom/files_mindmap/pull/190

**Comment by ChrWieg** [comment] 2023-12-22 09:12
Unfortunately I have the same issue with NC 28.0.1

**Comment by bandarrex** [comment] 2023-12-25 13:03
also  I have the same issue with NC 28.0.1 😌

**Comment by admorgan** [comment] 2023-12-28 22:52
I also have the same issue with NC 28.0.1

**Comment by Olib-48** [comment] 2024-01-03 16:28
I also have the same issue with Nextcloud Hub 7 (NC 28.0.1)

**Comment by 4001982248998** [comment] 2024-01-09 10:43
May I take the liberty of asking how this fix can be applied to solve the problem?

**Comment by artonge** [comment] 2024-01-09 15:39
The PR need to be merged, and a release need to be published.
If you really need it now, you could clone the repo, build a new version, and copy the result in your app folder.

**Comment by les-les** [comment] 2024-01-21 17:27
anyone a kind of idea when this is gonna happen ? 

sounds kind of fun to clone the repo build a new version and copy result to app folder 
but no clue how to do this .. 

;(

**Comment by xetyr** [comment] 2024-01-22 09:09
> Should be fixed by #190

Hey artonge, I download and copy paste your files on my files_mindmap directory, but I still can't open my .km files.
Logs show me the error "Could not find resource files_mindmap/js/files_mindmap-mindmap.js to load".
Indeed, the script is not called like that.

Did I missed something to use your repo ?

**Comment by ernolf** [comment] 2024-01-30 21:50
@les-les:
> but no clue how to do this ..

@xetyr:
> Did I missed something to use your repo ?

If you don't know how to check out, merge and build an app repo, than please come over to https://help.nextcloud.com/t/nc28-mindmap-km-files-not-working/176809/11?u=ernolf
I have created a build with the #190 PR, so you can try it out on your server.

ernolf

**Comment by xetyr** [comment] 2024-01-31 05:38
@ernolf 

Apparently I don't know how to do this haha. Your archive helped me, it's working now. Thank you so much !

**Comment by architectonio** [comment] 2024-01-31 06:48
I can confirm, the archive "files_mindmap-0.0.30.190.tar.gz" works lioke a charm!
Thank you very much @ernolf!

**Comment by juventas** [comment] 2024-02-05 12:32
The patched version didn't work for me at first. After I had activated "Limit to groups", all group members were able to use Mind Map. I then deactivated it again and now it works for everyone again.

**Comment by doitux** [comment] 2024-02-07 13:12
> I can confirm, the archive "files_mindmap-0.0.30.190.tar.gz" works like a charm! Thank you very much @ernolf!

What happens if I add this patched tar.gz version and there is an updated version (0.0.31) from the NC appstore? Will an update work without problem? Or do i have to remove something manually?

**Comment by tjakober** [comment] 2024-02-08 17:56
Same here: NC 28.0.2
The app can be installed, The symbol shows up beside a .kn file. However clicking on it just downloads the file,

**Comment by admorgan** [comment] 2024-02-08 19:24
> > I can confirm, the archive "files_mindmap-0.0.30.190.tar.gz" works like a charm! Thank you very much @ernolf!
> 
> What happens if I add this patched tar.gz version and there is an updated version (0.0.31) from the NC appstore? Will an update work without problem? Or do i have to remove something manually?

An updated 0.0.31 will update normally.

**Comment by whisky23** [comment] 2024-02-23 07:28
> Same here: NC 28.0.2 The app can be installed, The symbol shows up beside a .kn file. However clicking on it just downloads the file,

Hi, are there any news about it? I've got the same issue, although I have installed patch 0.0.30.190.

**Comment by alimnette** [comment] 2024-03-13 18:49
I also have the same issue with NC 28.0.1

**Comment by michauk** [comment] 2024-03-25 17:05
Hi guys. I ended up quitting this idea of running this software anymore.
I installed a quick&dirty NC27 docker instance, put my 2 km files in it, extracted what I needed and I'll be done with this in a few days when I get everything I want from my km files.

This software seems abandonned, Right, I really can understand the dev has no free time anymore.

When I installed this new docker instance, even downloading the plugin went wrong, it tried to download a file on a strange server, not related to midmap nor nextcloud nor whatever serious.
Now I'm trying to find another solution, self-hosted if possible.
Anyway, thanks for the great job until then.

**Comment by Mer0me** [comment] 2024-03-25 17:37
> Hi guys. I ended up quitting this idea of running this software anymore. I installed a quick&dirty NC27 docker instance, put my 2 km files in it, extracted what I needed and I'll be done with this in a few days when I get everything I want from my km files.
> 
> This software seems abandonned, Right, I really can understand the dev has no free time anymore.
> 
> When I installed this new docker instance, even downloading the plugin went wrong, it tried to download a file on a strange server, not related to midmap nor nextcloud nor whatever serious. Now I'm trying to find another solution, self-hosted if possible. Anyway, thanks for the great job until then.

Same decision for me.
I think draw.io into Nextcloud is a good alternative. What do you think ?
No offense for the maintainers of files_mindmap, that was a great job !

**Comment by architectonio** [comment] 2024-03-25 18:26
Here my two cents about the discussion hoping it will help.
There is no need to install a "NC 27" instance to recover/export the "km" files, since thanks to @ernolf the archive "files_mindmap-0.0.30.190.tar.gz" works like a charm on "NC 28" (I am using it on my NC 28 instance with no noticeable issues)
In addition of this, there is a Desktop Tool to create/edit the "km" files. It works on Linux, Windows and Mac.
Just download, run it on your Workstation and offline modify all your "km" mindmaps. The tool is DesktopNaoutu.
I work on my files both ways, from nextcloud and also with the local tool. (in the same way as I do with my draw.io diagrams).

**Comment by Mer0me** [comment] 2024-03-25 18:54
> Here my two cents about the discussion hoping it will help. There is no need to install a "NC 27" instance to recover/export the "km" files, since thanks to @ernolf the archive "files_mindmap-0.0.30.190.tar.gz" works like a charm on "NC 28" (I am using it on my NC 28 instance with no noticeable issues) In addition of this, there is a Desktop Tool to create/edit the "km" files. It works on Linux, Windows and Mac. Just download, run it on your Workstation and modify offline all your "km" mindmaps. The tool is DesktopNaoutu. I work on my files both ways, from nextcloud and also with the local tool. (in the same way as I do with my draw.io diagrams).

Does the unofficial patch work for link shared maps ? This is the missing point for me.

**Comment by tjakober** [comment] 2024-03-25 19:06
Yes I can confirm this. I replaced the folder "nextcloud\config\www\nextcloud\apps\files_mindmap\" with the folder "files_mindmap" of the mentioned archive "files_mindmap-0.0.30.190.tar.gz". Then it worked all again like in the previous Nectcloud versions.

**Comment by architectonio** [comment] 2024-03-25 19:27
> > Here my two cents about the discussion hoping it will help. There is no need to install a "NC 27" instance to recover/export the "km" files, since thanks to @ernolf the archive "files_mindmap-0.0.30.190.tar.gz" works like a charm on "NC 28" (I am using it on my NC 28 instance with no noticeable issues) In addition of this, there is a Desktop Tool to create/edit the "km" files. It works on Linux, Windows and Mac. Just download, run it on your Workstation and modify offline all your "km" mindmaps. The tool is DesktopNaoutu. I work on my files both ways, from nextcloud and also with the local tool. (in the same way as I do with my draw.io diagrams).
> 
> Does the unofficial patch work for link shared maps ? This is the missing point for me.

Yes it does

**Comment by architectonio** [comment] 2024-03-25 19:35
> > Here my two cents about the discussion hoping it will help. There is no need to install a "NC 27" instance to recover/export the "km" files, since thanks to @ernolf the archive "files_mindmap-0.0.30.190.tar.gz" works like a charm on "NC 28" (I am using it on my NC 28 instance with no noticeable issues) In addition of this, there is a Desktop Tool to create/edit the "km" files. It works on Linux, Windows and Mac. Just download, run it on your Workstation and modify offline all your "km" mindmaps. The tool is DesktopNaoutu. I work on my files both ways, from nextcloud and also with the local tool. (in the same way as I do with my draw.io diagrams).
> 
> Does the unofficial patch work for link shared maps ? This is the missing point for me.

A "Shared Link" downloads the file
However sharing the file with other users works

**Comment by michauk** [comment] 2024-03-25 20:01
> Here my two cents about the discussion hoping it will help. There is no need to install a "NC 27" instance to recover/export the "km" files, since thanks to @ernolf the archive "files_mindmap-0.0.30.190.tar.gz" works like a charm on "NC 28" (I am using it on my NC 28 instance with no noticeable issues) In addition of this, there is a Desktop Tool to create/edit the "km" files. It works on Linux, Windows and Mac. Just download, run it on your Workstation and modify offline all your "km" mindmaps. The tool is DesktopNaoutu. I work on my files both ways, from nextcloud and also with the local tool. (in the same way as I do with my draw.io diagrams).

Nice suggestion. But inaotu.org says "latest gthub release" in 2019. I won't move to another end-of-life desktop solution. Anyway, as a temporary solution to get my km content, it may be easier than a whole nextcloud instance.

No matter the hotfix, shared km can't be opened. 6 months with no real solution, it's way time to move.
Regards

**Comment by architectonio** [comment] 2024-03-25 20:48
> > Here my two cents about the discussion hoping it will help. There is no need to install a "NC 27" instance to recover/export the "km" files, since thanks to @ernolf the archive "files_mindmap-0.0.30.190.tar.gz" works like a charm on "NC 28" (I am using it on my NC 28 instance with no noticeable issues) In addition of this, there is a Desktop Tool to create/edit the "km" files. It works on Linux, Windows and Mac. Just download, run it on your Workstation and modify offline all your "km" mindmaps. The tool is DesktopNaoutu. I work on my files both ways, from nextcloud and also with the local tool. (in the same way as I do with my draw.io diagrams).
> 
> Nice suggestion. But inaotu.org says "latest gthub release" in 2019. I won't move to another end-of-life desktop solution. Anyway, as a temporary solution to get my km content, it may be easier than a whole nextcloud instance.
> 
> No matter the hotfix, shared km can't be opened. 6 months with no real solution, it's way time to move. Regards

I fully understand your standpoint. 
I`ll still wait a while, since I have a lot of km files and unfortunately, at this time, there is no working alternative on nextcloud. 
The same is for DesktopNaoutu, the 2019` version works well on all my Linux and Windows workstations.
Best regards

**Comment by ER-EPR** [comment] 2024-04-07 08:25
When will this NC28 fix be pushed to the store?

**Comment by micker** [comment] 2024-04-11 08:12
same return here 28.0.4

**Comment by priolumi** [comment] 2024-04-11 13:32
I (and probably the whole world) wait desperately and drumming my fingers for the solution. I've been looking for an alternative and can't find anything.
![mee_too_proc](https://github.com/ACTom/files_mindmap/assets/87815872/2541013a-db21-4b29-88dd-1613bc3bc44a)

**Comment by dualizeo** [comment] 2024-04-12 03:38
Perhaps if we can all pitch in some money to hire an offshore developer to fix it? it's php so it shouldn't be a problem

I also tried WiseMapping on docker but it's too simple, For now I'm still on Nextcloud 27.1.8 since it still works fine.
Also if you use obisidan canvas mind mapping it works nice for mapping similar to this app

**Comment by Mer0me** [comment] 2024-04-12 06:07
Have you tried draw.io app on Nextcloud ? It can do mind maps and many other things.

**Comment by architectonio** [comment] 2024-04-12 06:44
again, thanks to @ernolf the archive "files_mindmap-0.0.30.190.tar.gz" works like a charm on "NC 28" (I am using it on my NC 28 instance with no noticeable issues).
In addition of this, there is a Desktop Tool to create/edit the "km" files. It works on Linux, Windows and Mac.
Just download, run it on your Workstation and modify offline all your "km" mindmaps.
The tool is DesktopNaotu.
I work on my files in both ways, from nextcloud and also with the local tool. (in the same way as I do with my draw.io diagrams).

**Comment by priolumi** [comment] 2024-04-12 08:43
> Have you tried draw.io app on Nextcloud ? It can do mind maps and many other things.
draw.io isn't capable of loading km files , i fear . and there are nextclud installations hosted by providers that don't dare to install anything besides the official app-store, what is obvious very ok

**Comment by priolumi** [comment] 2024-04-12 08:49
draw.io can't load km files and there are providers that can't darte to install anything besides the nextcloud app store. (obviuos)
Thanks for mentioning the DektopNaotu (https://github.com/NaoTu/DesktopNaotu) , that could be a viable solution .. :)

**Comment by Mer0me** [comment] 2024-04-12 08:58
draw.io is on the nextcloud app store : https://apps.nextcloud.com/apps/drawio
It cannot open km files, but I believe it's a very confidential file format.

**Comment by grinapo** [comment] 2024-04-12 09:46
> Have you tried draw.io app on Nextcloud ? It can do mind maps and many other things.

No it cannot. It is a **drawing application** and what you draw is **fixed**. 
The point of mindmapping apps is that you only define hierarchy and the display and organisation is handled by the app. Also they offer mindmap oriented functions like prune/graft (aka move/re-attach), reorder, open/close subtree, and various metadata handling.

It is possible to use drawio to create a static drawing and call it a mindmap, and also record metadata which is there but neither displayed nor handled, that's probably all about it. 

Also it's been said (https://github.com/ACTom/files_mindmap/issues/191#issuecomment-2051094686) that **there is already a working version** of mindmap, it's just not merged and published.

**Comment by Mer0me** [comment] 2024-04-12 10:29
@grinapo  ok, I see what you expect from a mind map tool that I do not. Automatic display and organization of the map by the app is precisely a **problem** for me. 
The _working version_ can not display shared map without downloading it, and that is another problem for me.

**Comment by dualizeo** [comment] 2024-05-02 17:23
Yay 🙌 I can confirm the Forum fix worked!!! It Worked on 28.0.3!! I can open my mindmaps now the latest NextCloud 😃!
 from the forum admin [ernolf](https://help.nextcloud.com/t/nc28-mindmap-km-files-not-working/176809/11) and confirmed steps from [fanThomas ](https://help.nextcloud.com/t/nc28-mindmap-km-files-not-working/176809/16)

**Tutorial**
For Easy Instructions follow my tutorial but you need root access to your server:

1. Open your browser and login to your NextCloud account and make a folder in files called mindmapapp 
2. Download the **files_mindmap-0.0.30.190.tar** that ernolf provided from his link in the forum https://help.nextcloud.com/t/nc28-mindmap-km-files-not-working/176809/11?u=hewwo
3. From your browser now drag the file so you can Upload it to your mindmapapp folder you created
4. Now connect to your nextcloud server via ssh for example root@your-ip-address  ( if your logged in as different user then do `sudo -i `( to swap over as root ) and it will ask you to enter your password, the same one you used to log in
5. find the directory where your **Users** reside, for me it's `mnt/ncdata/` So you can type `ls` to show the current directory your in, or type `cd .. ` to go back into the directory then type `ls` again to see where you are at, and if you don't see it just type `cd /var/www/` IF You don't see users it could also be in the following places:
`/var/www/nextcloud/data/your-user-name/files/mindmapapp`
Or `/var/snap/nextcloud/common/nextcloud/data/your-user-name/files/mindmapapp`
6. Now once your inside the mindmapp directory copy **files_mindmap-0.0.30.190.tar** by doing command: `cp files_mindmap-0.0.30.190.tar var/www/nextcloud/apps`
7. And now to extract and replace do `tar -xvzf files_mindmap-0.0.30.190.tar.gz` hit tab on windows so it auto fills the file name Or Manually type it Lol ( You might want to cd into nextcloud/apps and confirm that's where files_mindmap folder is already there as your going to just overwrite it )
8. remove the files_mindmap-0.0.30.190.tar.gz from the apps folder `rm files_mindmap-0.0.30.190.tar.gz`
9. feel free to go back to your created folder and delete the mindmapapp folder and Test it out! 😊

Can someone fork it so they can submit it to the App store so we can 1 click in stall it? OR Post in the Forum like I did so it will be noticed and someone can do it from NextCloud

I also made sure I scanned it for viruses see image below
VirusScan to be safe:
<img width="950" alt="scan" src="https://github.com/ACTom/files_mindmap/assets/60861619/c8eddb45-ca50-4e44-a7aa-feb69abd5f9c">

**Comment by architectonio** [comment] 2024-05-02 17:55
Good Job @dualizeo!
It also works on NextCloud 28.0.5

**Comment by tjakober** [comment] 2024-05-02 18:34
And it works still in NextCloud 29!

Thaks alot.


architectonio ***@***.***> schrieb am Do. 2. Mai 2024 um
19:55:

**Comment by HanSolo361** [comment] 2024-05-04 14:59
Thanks a lot @dualizeo for the clear tutorial and all the previous contributors!!!

**I also had to fix the .mjs handling on my nginx server**, as mentioned [here](https://help.nextcloud.com/t/activity-and-logging-sections-in-admins-setting-shows-blank-pages/175958/4), which I had been overseeing.

**Comment by nokia001** [comment] 2024-06-10 04:42
It still not working. Only Download. 
NC 28.0.6
NC 29.0.2

**Comment by mementomori74** [comment] 2024-06-19 09:41
is there an update in the works?

**Comment by ernolf** [comment] 2024-07-02 11:28
> Tutorial

The easy way: https://github.com/ACTom/files_mindmap/issues/197#issuecomment-2202831303

**Comment by Sicoval31** [comment] 2024-10-10 08:32
Thanks, it's works with snap install.
Only edition work, shared files not

**Comment by ACTom** [comment] 2024-10-27 15:24
It's in the works and should be updated soon.

**Comment by ACTom** [comment] 2024-11-28 01:59
see https://github.com/ACTom/files_mindmap/issues/203

**Closed by ACTom** 2024-11-28 01:59 UTC

**Comment by stephancordes** [comment] 2026-04-11 00:56
Yes, i spend two days with Claud Code and now the App works with NC 33. There are a lot of changes in the code. Updatet today again. Some old bugs are gone now. - Maybe it is not perfekt, but it works.

**Comment by AndyScherzinger** [comment] 2026-04-11 08:46
Hi @stephancordes 

see also my initial comment on the PR at https://github.com/nextcloud/files_mindmap/pull/259#issuecomment-4222273689

Nice work and happy you went into the topic of making it compatible and fixing various issues of the app :pray:

Yet just to be on  the same page hence the question from the above referenced post on compatibility fixes, given 

* https://github.com/nextcloud/files_mindmap/pull/247 added v34 compatibility
* https://github.com/nextcloud/files_mindmap/pull/243 added v33 compatibility
* https://github.com/nextcloud/files_mindmap/pull/233 added v32 compatibility

In any way, please feel free to ping me and @miaulalala when you think the PR is ready for a review and some testing and a pre-release.

**Comment by stephancordes** [comment] 2026-04-11 10:34
Hi @AndyScherzinger and @miaulalala,
Perhaps it would have been wise to look for other forks and information regarding new builds. I overlooked that.
The fact that Claude went completely haywire with the commits is entirely on me. This is my first time working with this tool. Next time, I’ll do more intermediate testing and have Claude make fewer commits. The whole thing was originally planned merely as a quick CN33 compatibility update, but it ended up becoming something more substantial:
- Compatible with N33
- Compatible with PHP 8.5
- Resolved Val 2 / Val 3 conflicts
- Firefox CSS fixes (text had shifted upwards)
- .mm files are now automatically converted to .km files, with a notification for the user
- Added a check to see if a .km file already exists, along with an option to rename it via a dialog box (including corresponding entries in the language files)
- Fixed an issue where NC wouldn't recognize the newly written file
- Reduced the size of the header area (otherwise it was barely usable on a smartphone)
- Restored accessibility for the auto-save checkbox, the save button, and the export drop-down menu

I only spent about an hour working with the app. To me, it looked ready to be deployed.

Oh—and Claude assigned me the username "root." I’m only just noticing that now.

Edit:
I see that you have discovered an error. I will take a look at it later.

**Comment by AndyScherzinger** [comment] 2026-04-11 11:37
Thanks a lot for the detailed reply @stephancordes - I am sure we figure things out together along the way and I am looking forward to the improvements and fixes 👍

**Comment by stephancordes** [comment] 2026-04-11 11:53
I fexed the conflicts in my fork
