### ISSUE TITLE
SyntaxError: JSON.parse: unexpected end of data at line 1 column 2 of the JSON data

### ISSUE THREAD

**Issue by SwoosOfficial** [ACTom/files_mindmap#94] opened 2020-03-14 11:27 UTC
When creating a new km. 

However when i rename it to .md it opens. 
But neither saving nor reopening works. Obviously some File i/O Problem, but all acess rights are well working with all other apps (eg markdown editor)

Server: 

Nextcloud v18.0.0
OS: Raspian
Hardware: Raspberry Pi 4

Client:

Firefox 74.0 & Chromium 80.0
Ubuntu 19.10

**Comment by SwoosOfficial** [comment] 2020-03-14 13:23
P.S.: Syslog, phpfpm_log and Protocol empty.

**Comment by t-markmann** [comment] 2020-03-14 13:24
This happens to me as well on NC 17.0.3

Workaround: take an old, empty .mk file. The app seems to create the new files from a defective template.

**Comment by vasyugan** [comment] 2020-03-14 13:28
> This happens to me as well on NC 17.0.3
> 
> Workaround: take an old, empty .mk file. The app seems to create the new files from a defective template.

Where do I get one?

**Comment by t-markmann** [comment] 2020-03-14 13:34
Try this one: [mindmap.zip](https://github.com/ACTom/files_mindmap/files/4332825/mindmap.zip)

**Comment by SwoosOfficial** [comment] 2020-03-14 13:40
Do you know the folder where the template lies. Then i just replace the template file. 🤔

**Comment by SwoosOfficial** [comment] 2020-03-14 13:43
> Try this one: [mindmap.zip](https://github.com/ACTom/files_mindmap/files/4332825/mindmap.zip)

Workaround work for a single file! Thanks.

**Comment by ACTom** [comment] 2020-03-14 14:00
Oh! This is a bug caused by the introduction of a new supported format. I have not tested the newly created file before, and I will fix it now.

**Comment by ACTom** [comment] 2020-03-14 14:41
Fixed in v0.0.20

**Closed by ACTom** 2020-03-14 14:41 UTC
Labels: bug
